### ISSUE TITLE
회원가입 오류

### ISSUE THREAD

**Issue by kkongkeozzang** [kkongkeozzang/UnderTheMoon#46]
# 발생 일시
2022.01.23
# 발생 위치
signup.jsp
# 증상
HTTP 상태 500 – 내부 서버 오류
### Cause: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("ADMIN"."MEMBER"."MEMBER_ZIPCODE")

; ORA-01400: cannot insert NULL into ("ADMIN"."MEMBER"."MEMBER_ZIPCODE")
; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("ADMIN"."MEMBER"."MEMBER_ZIPCODE")
]을(를) 발생시켰습니다.
Error : 1400, Position : 75, Sql = insert into member values(member_id_seq.nextval,:1 ,:2 ,:3 ,:4 
  	, :5 , :6 , :7 , :8 , default, '별', 'ROLE_USER', :9 ), OriginalSql = insert into member values(member_id_seq.nextval,?,?,?,?
  	, ?, ?, ?, ?, default, '별', 'ROLE_USER', ?), Error Msg = ORA-01400: cannot insert NULL into ("ADMIN"."MEMBER"."MEMBER_ZIPCODE")
# 재현 방법
아이디/비번/이름/이메일/생년월일/휴대폰만 쓰고 가입버튼 누름
# 스크린샷(선택)
![image](https://user-images.githubusercontent.com/86351381/150682855-2240d749-336a-4e40-8f3b-20d95ba29a16.png)

**Comment by kkongkeozzang** [comment]
그리고 개인정보 동의 안해도 가입됩니다..

**Comment by kkongkeozzang** [comment]
이메일에 * 없는데 유효성 검사에 걸립니다

**Comment by jhleeeeeeee** [comment]
해결 완료!
