### ISSUE TITLE
상품 입력 오류

### ISSUE THREAD

**Issue by kkongkeozzang** [kkongkeozzang/UnderTheMoon#78]
# 발생 일시
2022.01.27
# 발생 위치
판매자-> 상품등록
# 증상
상품 등록 한번 하고 한번 더하려고하니 아래와 같이 오류 남
# 재현 방법
스샷 참조
# 스크린샷(선택)
![image](https://user-images.githubusercontent.com/86351381/151370483-02d1bbf2-bb2d-473d-ac45-ebecfca0c684.png)

### Cause: java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (ADMIN.SYS_C007911) violated

; ORA-00001: unique constraint (ADMIN.SYS_C007911) violated
; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (ADMIN.SYS_C007911) violated
]을(를) 발생시켰습니다.
Error : 1, Position : 0, Sql = insert into md values(69, :1 ,:2 ,:3 ,:4 ,:5 ,:6 ,:7 ,:8 ), OriginalSql = insert into md values(69, ?,?,?,?,?,?,?,?), Error Msg = ORA-00001: unique constraint (ADMIN.SYS_C007911) violated

**Comment by craving4u** [comment]
sql을 .nextval로 수정하고 sequence 시작 번호 100으로 수정해두겠습니다~

**Comment by craving4u** [comment]
<insert id="insertMd">
		insert into md values(md_id_seq.nextval, #{md_region},#{md_name},#{md_content},#{md_price},#{md_category},#{md_abv},#{md_image},#{md_detail_image})
</insert>
